title: <p align="center"> Manu Sijaria </p>
logo: /assets/img/IMG.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manu-sijaria/">LinkedIn</a> |
  <a href="https://github.com/manusijaria">GitHub</a>
  
  <br>   
  • A qualified and competent professional with 14 years of experience in IT Industry which includes around 6 years of experience in Hadoop Ecosystem, Spark.
  • Currently working as Lead Data Engineering working actively in AWS Cloud , Big Data pipelines, Spark, Python , CI CD.
  • Persuing Masters in Machine Learning & Artificial Intelligence.	
  •	Cloudera Certified CCA 175 Spark and Hadoop developer [2021]
  •	Google Essential  Cloud Infrastructure : Foundation  by Coursera [2019]
  •	Google Cloud Platform Fundamentals : Core Infrastructure by Coursera [2019]
  •	Certified Scrum Master  by ScrumAlliance [2020]
  •	Cloudera Certified Hadoop & Spark Developer (CCA-175) [2021]
  •	Hands on exeperince in working with Scala, Python , Core Java, J2EE and SQL.
  •	Extensive experience in Software development life Cycle (SDLC)
  •	Having Good onsite experience in working with client like Dagrofa (DENMARK), Jibun Bank (JAPAN).
  •	Experience in Soap & Rest, Ajax.
  •	A Team Player.
  •	Having Good knowledge of capacity planning of Multi node Cluster Configurations.
  •	Excellent verbal, written and communication skills.
  •	Self-motivated and ready to learn new Technologies.
  •	C-DAC certified from IASCD, D.Y. Patil College, Pune (2009 batch).
  •	Competency is resolving live production issues.
  •	Hands on experience in debugging & problem solving.

  <br>
  </p>



theme: jekyll-theme-minimal
