title: <p align="center"> Manu Sijaria </p>
logo: /assets/img/IMG.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manu-sijaria/">LinkedIn</a> |
  <a href="https://github.com/manusijaria">GitHub</a>
  <br>
    A qualified and competent professional with 14 years of experience in IT Industry.Currently working as Lead Data Engineering working actively in AWS Cloud ,Big Data , Hadoop Ecosystem , Data pipelines, Spark, Python , CI CD.
  </br>
  </p>


theme: jekyll-theme-minimal
