title: <p align="center"> Manu Sijaria </p>
logo: /assets/img/IMG.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manu-sijaria/">LinkedIn</a> |
  <a href="https://github.com/manusijaria">GitHub</a>
certifications : Google Essential  Cloud Infrastructure : Foundation  by Coursera [2019],  Google Cloud Platform Fundamentals : Core Infrastructure by Coursera [2019] ,Certified Scrum Master  by ScrumAlliance [2020] ,Cloudera Certified Hadoop & Spark Developer (CCA-175) [2021]

  </p>



theme: jekyll-theme-minimal
